-- Ensure every monthly partition exists, and drop ones past the retention window.
--
--   psql "$DATABASE_URL" -f db/partition.sql
--   KEEP_MONTHS=24 psql "$DATABASE_URL" -f db/partition.sql   # optional
--
-- Run from cron, monthly. Two things it must get right:
--
-- 1. It backfills EVERY month from the retention floor to next month, not just
--    the next one. A fresh install has no partitions at all, and a site that
--    imports history needs months that are already current. Creating only "next
--    month" makes every insert in a gap fail with "no partition of relation
--    found for row" — a miserable thing to debug from an error that the
--    tracker swallowed in a browser.
--
-- 2. It creates NO indexes. `CREATE INDEX` on a partitioned parent automatically
--    propagates to every existing partition and every partition created later,
--    so per-partition index creation here would only duplicate work.
--
-- The month list is generated by Postgres rather than by shell `date`, because
-- the two flag sets (-d vs -v) differ between GNU and BSD and this file has to
-- behave the same on an operator's laptop and in a container. Retention is read
-- from a GUC rather than a psql variable because psql deliberately does not
-- interpolate variables inside dollar-quoted blocks.
--
-- There is deliberately no default partition: an insert that finds no matching
-- partition should fail loudly rather than land somewhere nobody will query.
DO $$
DECLARE
  keep_m  int    := coalesce(nullif(current_setting('loudmetric.keep_months', true), '')::int, 12);
  m       date;
  ym      text;
  nxt     date;
  created int    := 0;
  dropped text[] := '{}';
BEGIN
  -- Retention floor through the start of next month, month by month.
  FOR m IN
    SELECT gs::date
      FROM generate_series(
             date_trunc('month', now()) - make_interval(months => keep_m),
             date_trunc('month', now()) + interval '1 month',
             interval '1 month'
           ) AS gs
  LOOP
    ym := to_char(m, 'YYYYMM');
    nxt := m + interval '1 month';

    IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'events_' || ym) THEN
      EXECUTE format(
        'CREATE TABLE events_%s PARTITION OF events FOR VALUES FROM (%L) TO (%L)',
        ym, m, nxt
      );
      created := created + 1;
    END IF;
  END LOOP;

  -- Retention: detach and drop whole partitions. Instant, and it does not bloat
  -- the table the way a DELETE would.
  FOR ym IN
    SELECT c.relname
      FROM pg_class c
        JOIN pg_inherits i ON i.inhrelid = c.oid
        JOIN pg_class t   ON t.oid = i.inhparent
     WHERE t.relname = 'events'
  LOOP
    IF substring(ym from '[0-9]{6}$')::int
       < to_char(now() - make_interval(months => keep_m), 'YYYYMM')::int
    THEN
      EXECUTE format('DROP TABLE IF EXISTS %I', ym);
      dropped := dropped || ym;
    END IF;
  END LOOP;

  RAISE NOTICE 'created % partition(s); dropped %',
    created, coalesce(array_to_string(dropped, ', '), 'none');
END $$;
